query Constellations($filter: ConstellationFilter) {
  constellations(filter: $filter) {
    items {
      id
      name
      solarSystemCount
    }
    pageInfo {
      currentPage
      totalPages
      totalCount
      hasNextPage
      hasPreviousPage
    }
  }
}

query Constellation($id: Int!) {
  constellation(id: $id) {
    id
    name
    solarSystemCount
    sovereignty {
      ownerType
      ownerId
      ownerName
      allianceTicker
      systemCount
    }
    region {
      id
      name
    }
    solarSystems {
      id
      name
      securityStatus
      security_class
      latestKills {
        ship_kills
        pod_kills
        npc_kills
        timestamp
      }
    }
  }
}
