"use client";

import { ApolloProvider } from "@apollo/client";
import Footer from "../components/Footer/Footer";
import Header from "../components/Header/Header";
import apolloClient from "../lib/apolloClient";
import "./globals.css";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen antialiased bg-gray-50">
        <ApolloProvider client={apolloClient}>
          <Header />

          {/* Main Content */}
          <main className="flex-1 w-full px-4 py-8 mx-auto max-w-7xl sm:px-6 lg:px-8">
            {children}
          </main>

          <Footer />
        </ApolloProvider>
      </body>
    </html>
  );
}
