blank_issues_enabled: false
contact_links:
  - name: 💬 Question or Discussion
    url: https://github.com/umutyerebakmaz/killreport/discussions
    about: Ask questions or discuss ideas with the community
  - name: 📚 Documentation
    url: https://github.com/umutyerebakmaz/killreport#readme
    about: Check out our documentation and guides
